# Generated by Django 5.1.7 on 2025-04-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_historico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizacao',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
